// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/[browser]/index.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/ChartProvider.tsx";
import * as $$1 from "./islands/FeatureRow.tsx";
import * as $$2 from "./islands/Version.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/[browser]/index.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/ChartProvider.tsx": $$0,
    "./islands/FeatureRow.tsx": $$1,
    "./islands/Version.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
